name: Validate Metadata

on:
  push: 
    branches: 
      - automation/update-pr-status
  pull_request:
    branches: [main]
    paths:
        - '**/modernization-metadata/**'
  issue_comment:
    types: [created]

permissions:
  pull-requests: write

jobs:
  validate-metadata:
    if: |
      github.event_name == 'pull_request' ||
      (github.event_name == 'issue_comment' &&
       github.event.issue.pull_request &&
       contains(github.event.comment.body, 'run-checks'))
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2

      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 #v5.6.0
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: pip install requests PyGithub jsonschema

      - name: Get PR number (only for push event)
        if: github.event_name == 'push'
        id: get_pr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_NUMBER=$(gh pr view --json number -q .number || echo "")
          echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_ENV
          echo "PR Number: $PR_NUMBER"

      - name: Set PR number from pull_request event
        if: github.event_name == 'pull_request'
        run: echo "PR_NUMBER=${{ github.event.number }}" >> $GITHUB_ENV

      - name: Set PR number from issue_comment event
        if: github.event_name == 'issue_comment'
        run: echo "PR_NUMBER=${{ github.event.issue.number }}" >> $GITHUB_ENV

      - name: Validate metadata
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ env.PR_NUMBER }}
        run: python scripts/validate_metadata.py