name: Validate Metadata PR

on:
  pull_request:
    branches: [main]
    paths:
      - '**/modernization-metadata/**'

permissions:
  pull-requests: write

jobs:
  validate-metadata:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests PyGithub jsonschema

      - name: Validate metadata
        env:
          MY_PAT: ${{ secrets.PAT }}
        run: python scripts/validate_metadata.py

      - name: Check if PR is from a bot fork
        id: bot_check
        run: |
          echo "PR_AUTHOR=${{ github.actor }}" >> $GITHUB_ENV
          if [[ "${{ github.actor }}" =~ bot$ || "${{ github.actor }}" =~ \[bot\]$ ]]; then
            echo "IS_BOT=true" >> $GITHUB_ENV
          else
            echo "IS_BOT=false" >> $GITHUB_ENV
          fi
          if [[ "${{ github.event.pull_request.head.repo.full_name }}" != "${{ github.repository }}" ]]; then
            echo "IS_FORK=true" >> $GITHUB_ENV
          else
            echo "IS_FORK=false" >> $GITHUB_ENV
          fi

      - name: Auto-merge PR
        if: env.IS_BOT == 'true' && env.IS_FORK == 'true' && success()
        run: gh pr merge "${{ github.event.pull_request.number }}" --merge --auto --repo ${{ github.repository }}
        env:
          GH_TOKEN: ${{ secrets.PAT }}
